// Generated by CoffeeScript 1.9.3

/*global describe, beforeEach, it */

(function() {
  'use strict';
  var chai, exec, expect, fs, helpers, path;

  path = require('path');

  helpers = require('yeoman-generator').test;

  chai = require('chai');

  expect = chai.expect;

  fs = require('fs-extra');

  exec = require('child_process').exec;

  describe('angular-meteor generator', function() {
    var defaultOptions, gen, generatorTest;
    gen = void 0;
    defaultOptions = {
      script: 'coffee',
      markup: 'jade',
      stylesheet: 'stylus',
      material: true,
      bower: true,
      auth: true,
      oauth: []
    };
    generatorTest = function(generatorType, name, mockPrompt, callback) {
      gen.run({}, function() {
        var amGenerator, deps;
        amGenerator = void 0;
        deps = [path.join('../..', generatorType)];
        amGenerator = helpers.createGenerator('angular-meteor:' + generatorType, deps, [name]);
        helpers.mockPrompt(amGenerator, mockPrompt);
        amGenerator.run([], function() {
          callback();
        });
      });
    };
    beforeEach(function(done) {
      var deps;
      this.timeout(10000);
      deps = ['../../app'];
      helpers.testDirectory(path.join(__dirname, 'temp'), (function(err) {
        if (err) {
          return done(err);
        }
        gen = helpers.createGenerator('angular-meteor:app', deps, ['test', 'dontrun']);
        done();
      }).bind(this));
    });
    describe('running app', function() {
      describe('with default options', function() {
        beforeEach(function() {
          helpers.mockPrompt(gen, defaultOptions);
        });
        it('should run happily', function(done) {
          this.timeout(60000);
          gen.run(function() {
            done();
          });
        });
        it('should pass jshint', function(done) {
          exec('grunt jshint', function(error, stdout, stderr) {
            expect(stdout).to.contain('Done, without errors.');
            done();
          });
        });
      });
    });
  });

}).call(this);
